### ISSUE TITLE
Crashes when downloading skyfactor 3

### ISSUE THREAD

**Issue by lyze237** [kaeedo/Cursed#1]
Hello!

I've tried to download skyfactory 3 today but the program crashes after a bit whenever I clicked on "download".

- https://mods.curse.com/modpacks/minecraft/256183-ftb-presents-skyfactory-3

Gets stuck while doing absolutely nothing.

- https://www.feed-the-beast.com/projects/ftb-presents-skyfactory-3

Crashes: http://pastebin.com/GetLrUx8

**Comment by kaeedo** [comment]
Thanks for the bug report. I'm assuming you're on Linux. Which distro and what desktop environment? Also, what mono packages do you have installed? To be on the safe side, I would suggest the ones listed here: http://www.mono-project.com/docs/getting-started/install/linux/#usage  but  I need to do more testing to see what exactly is necessary.

I won't be able to take a closer look at the bug until this weekend, so in the meantime I would suggest one of the other downloaders, such as: https://github.com/Vazkii/CMPDL

**Comment by lyze237** [comment]
Ah forgot to mention those things, sorry!

Xubuntu 16.10, xfce.

And I installed "mono-complete fsharp gtk sharp3"

**Comment by kaeedo** [comment]
I believe I fixed the issue. Can you try this: https://github.com/kaeedo/Cursed/releases/tag/v1.2.2

I tested it on a clean install of Xubuntu xfce in VirtualBox, with the only dependencies : mono-devel and gtk-sharp3.

Let me know how it works

**Comment by lyze237** [comment]
Awesome it works, thanks!
