### ISSUE TITLE
Error on downloading modpack

### ISSUE THREAD

**Issue by anagram3k** [kaeedo/Cursed#10]
The program starts but crashes when clicking "Download"

OS: Ubuntu 19.04
Installed: mono-devel gtk-sharp3

Arguments:
Extract location: /home/luis/Applications/multimc/instances
Modpack URL: https://www.curseforge.com/minecraft/modpacks/volcano-block

Crash log: https://pastebin.com/vyPGKKv8

**Comment by kaeedo** [comment]
Hi. Thanks for the report. I am actually no longer maintaining this program, as it is now possible to directly download modpacks from curse though Multi MC: https://www.reddit.com/r/feedthebeast/comments/6yhd90/how_to_download_curse_modpacks_with_only_multimc/

I'll update the readme to mention this as well.

It's still nice to know that some people have found this repository, and considered it worth a try. Thanks for that
