### ISSUE TITLE
Crashing on boot

### ISSUE THREAD

**Issue by GandalfTheHobbit** [kaeedo/Cursed#7]
When I try to run Cursed (with the command mono Cursed.Desktop.Exe) I get this error:

> [aaron@PC-64553 Cursed]$ mono Cursed.Desktop.exe
> 
> Unhandled Exception:
> System.InvalidOperationException: Could not detect platform. Are you missing a platform assembly?
>   at Eto.Platform.get_Detect () [0x000c6] in <ba1cd6b5277e44a1a2ea07b34eff2c44>:0 
>   at Cursed.Program.Main (System.String[] args) [0x00000] in <58c453eb5a8c4e87a7450383eb53c458>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.InvalidOperationException: Could not detect platform. Are you missing a platform assembly?
>   at Eto.Platform.get_Detect () [0x000c6] in <ba1cd6b5277e44a1a2ea07b34eff2c44>:0 
>   at Cursed.Program.Main (System.String[] args) [0x00000] in <58c453eb5a8c4e87a7450383eb53c458>:0

**Comment by kaeedo** [comment]
I'm going to assume you have the following: 
mono-devel
gtk-sharp3

I live in Germany, so I don't know if i'll get to it tonight. I'm pretty sure I know how to fix this
(famous last words)

**Comment by GandalfTheHobbit** [comment]
On arch linux, I couldnt find gtk-sharp3, but I've got mono-devel. I'll have a look for the gtk-sharp3 package quickly.

**Comment by GandalfTheHobbit** [comment]
I've found a gtk-sharp3 package, and it works now. But my console is flooded with the same warning message:
> (Cursed.Desktop:26508): Gtk-WARNING **: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node progress owner GtkProgressBar)

**Comment by kaeedo** [comment]
Well, that warning is just a warning. unfortunately that's very difficult to reproduce on different Distros, and as long as it *looks* like it works, I don't want to touch it :p

**Comment by GandalfTheHobbit** [comment]
All right, thanks for the help. For arch linux, the package I needed was gtk-sharp-3, if you want to include that anywhere.

**Comment by kaeedo** [comment]
Thanks, will do.
